name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull_requests: write
    steps:
      - name: Greet on first PR
        if: github.event_name == 'pull_request_target' && github.event.action == 'opened'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "🎉 Congratulations on opening your first pull request! Thank you for contributing to the project. We will review it as soon as possible. 🚀"
      - name: Greet on first Issue
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome, and thanks for your first issue! We appreciate you taking the time to contribute to the project. 🌟"
